### ISSUE TITLE
Getting an error when selecting the voice

### ISSUE THREAD

**Issue by outusuke** [Elleo/pied#24]
Nov 23 21:53:00 fedora com.mikeasoft.pied.desktop[8905]: [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PathNotFoundException: Creation failed, path = '/home/user/.config/speech-dispatcher' (OS Error: No such file or directory, errno = 2)
Nov 23 21:53:00 fedora com.mikeasoft.pied.desktop[8905]: #0      _Directory.createSync (dart:io/directory_impl.dart:124)
Nov 23 21:53:00 fedora com.mikeasoft.pied.desktop[8905]: #1      _VoiceSelectorState.setSDConfig (package:pied/voice_selector.dart:129)
Nov 23 21:53:00 fedora com.mikeasoft.pied.desktop[8905]: #2      _VoiceSelectorState.build.<anonymous closure>.<anonymous closure> (package:pied/voice_selector.dart:354)
Nov 23 21:53:00 fedora com.mikeasoft.pied.desktop[8905]: #3      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1170)
Nov 23 21:53:00 fedora com.mikeasoft.pied.desktop[8905]: #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:351)
Nov 23 21:53:00 fedora com.mikeasoft.pied.desktop[8905]: #5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:656)
Nov 23 21:53:00 fedora com.mikeasoft.pied.desktop[8905]: #6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:313)
Nov 23 21:53:00 fedora com.mikeasoft.pied.desktop[8905]: #7      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:246)
Nov 23 21:53:00 fedora com.mikeasoft.pied.desktop[8905]: #8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:703)
Nov 23 21:53:00 fedora com.mikeasoft.pied.desktop[8905]: #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98)
Nov 23 21:53:00 fedora com.mikeasoft.pied.desktop[8905]: #10     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143)
Nov 23 21:53:00 fedora com.mikeasoft.pied.desktop[8905]: #11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633)
Nov 23 21:53:00 fedora com.mikeasoft.pied.desktop[8905]: #12     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141)
Nov 23 21:53:00 fedora com.mikeasoft.pied.desktop[8905]: #13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127)
Nov 23 21:53:00 fedora com.mikeasoft.pied.desktop[8905]: #14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:501)
Nov 23 21:53:00 fedora com.mikeasoft.pied.desktop[8905]: #15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:481)
Nov 23 21:53:00 fedora com.mikeasoft.pied.desktop[8905]: #16     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:450)
Nov 23 21:53:00 fedora com.mikeasoft.pied.desktop[8905]: #17     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:426)
Nov 23 21:53:00 fedora com.mikeasoft.pied.desktop[8905]: #18     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:389)
Nov 23 21:53:00 fedora com.mikeasoft.pied.desktop[8905]: #19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:336)
Nov 23 21:53:00 fedora com.mikeasoft.pied.desktop[8905]: #20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:305)
Nov 23 21:53:00 fedora com.mikeasoft.pied.desktop[8905]: #21     _invoke1 (dart:ui/hooks.dart:328)
Nov 23 21:53:00 fedora com.mikeasoft.pied.desktop[8905]: #22     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442)
Nov 23 21:53:00 fedora com.mikeasoft.pied.desktop[8905]: #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:262)
Nov 23 21:53:00 fedora com.mikeasoft.pied.desktop[8905]: [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PathNotFoundException: Cannot open file, path = '/home/user/.config/speech-dispatcher/modules/piper.conf' (OS Error: No such file or directory, errno = 2)
Nov 23 21:53:00 fedora com.mikeasoft.pied.desktop[8905]: #0      _checkForErrorResponse (dart:io/common.dart:55)
Nov 23 21:53:00 fedora com.mikeasoft.pied.desktop[8905]: #1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
Nov 23 21:53:00 fedora com.mikeasoft.pied.desktop[8905]: <asynchronous suspension>
Nov 23 21:53:00 fedora com.mikeasoft.pied.desktop[8905]: #2      _File.writeAsBytes.<anonymous closure> (dart:io/file_impl.dart:634)
Nov 23 21:53:00 fedora com.mikeasoft.pied.desktop[8905]: <asynchronous suspension>

**Comment by outusuke** [comment]
Never mind, for some reason the Flatpak was lacking the /home permission even after reinstalling. I don't know why
